apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: marklogic
spec:
  selector:
    matchLabels:
      app: marklogic
  serviceName: "ml-service"
  replicas: 2
  template:
    metadata:
      labels:
        app: marklogic
      #annotations:
      #  pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: marklogic
          image: psychobmx/marklogic:v1
          imagePullPolicy: Always
          command: ["/opt/entry-point.sh"]
          ports:
            - containerPort: 7997
              name: health-check
            - containerPort: 7998
              name: cluster-port
            - containerPort: 7999
              name: cluster-port2
            - containerPort: 8000
              name: app-services
            - containerPort: 8001
              name: admin
            - containerPort: 8002
              name: manage
          lifecycle:
            preStop:
              exec:
                # SIGTERM triggers a quick exit; gracefully terminate instead
                command: ["/etc/init.d/MarkLogic stop"]
          volumeMounts:
            - name: ml-data
              mountPath: /var/opt/MarkLogic
          resources:
            requests:
              cpu: 1
              memory: 1Gi
      imagePullSecrets:
      - name: registry-secret
  volumeClaimTemplates:
    - metadata:
        name: ml-data
        # annotations:
        #   volume.beta.kubernetes.io/storage-class: standard
      spec:
        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: local-storage