apiVersion: v1
kind: PersistentVolume
metadata:
  name: dst-local-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/inoues/k8s-pv/pv-1"